CPP_FLAGS=-std=c++17 -Wshadow -Wall -D_GLIBCXX_DEBUG

all: 2117E

2117E: 2117E.cpp
	g++-14 $(CPP_FLAGS) -g 2117E.cpp -o 2117E

brute: brute.cpp
	g++-14 $(CPP_FLAGS) -g brute.cpp -o brute
	
gen: gen.cpp
	g++-14 $(CPP_FLAGS) -g gen.cpp -o gen
