CPP_FLAGS=-std=c++17 -Wshadow -Wall -D_GLIBCXX_DEBUG

all: usaco_15_dec_s_3

usaco_15_dec_s_3: usaco_15_dec_s_3.cpp
	g++-13 $(CPP_FLAGS) -g usaco_15_dec_s_3.cpp -o usaco_15_dec_s_3

brute: brute.cpp
	g++-13 $(CPP_FLAGS) -g brute.cpp -o brute
	
gen: gen.cpp
	g++-13 $(CPP_FLAGS) -g gen.cpp -o gen
