CPP_FLAGS=-std=c++17 -Wshadow -Wall -D_GLIBCXX_DEBUG

all: 1234A

1234A: 1234A.cpp
	g++-14 $(CPP_FLAGS) -g 1234A.cpp -o 1234A

brute: brute.cpp
	g++-14 $(CPP_FLAGS) -g brute.cpp -o brute
	
gen: gen.cpp
	g++-14 $(CPP_FLAGS) -g gen.cpp -o gen
