CPP_FLAGS=-std=c++17 -Wshadow -Wall -D_GLIBCXX_DEBUG

all: 2148F

2148F: 2148F.cpp
	g++-14 $(CPP_FLAGS) -g 2148F.cpp -o 2148F

brute: brute.cpp
	g++-14 $(CPP_FLAGS) -g brute.cpp -o brute
	
gen: gen.cpp
	g++-14 $(CPP_FLAGS) -g gen.cpp -o gen
