CPP_FLAGS=-std=c++17 -Wshadow -Wall -D_GLIBCXX_DEBUG

all: 2082B

2082B: 2082B.cpp
	g++-14 $(CPP_FLAGS) -g 2082B.cpp -o 2082B

brute: brute.cpp
	g++-14 $(CPP_FLAGS) -g brute.cpp -o brute
	
gen: gen.cpp
	g++-14 $(CPP_FLAGS) -g gen.cpp -o gen
