CPP_FLAGS=-std=c++17 -Wshadow -Wall -D_GLIBCXX_DEBUG

all: NAME

NAME: NAME.cpp
	g++-13 $(CPP_FLAGS) -g NAME.cpp -o NAME

brute: brute.cpp
	g++-13 $(CPP_FLAGS) -g brute.cpp -o brute
	
gen: gen.cpp
	g++-13 $(CPP_FLAGS) -g gen.cpp -o gen
