CPP_FLAGS=-std=c++17 -Wshadow -Wall -D_GLIBCXX_DEBUG

all: 2126F

2126F: 2126F.cpp
	g++-14 $(CPP_FLAGS) -g 2126F.cpp -o 2126F

brute: brute.cpp
	g++-14 $(CPP_FLAGS) -g brute.cpp -o brute
	
gen: gen.cpp
	g++-14 $(CPP_FLAGS) -g gen.cpp -o gen
