CPP_FLAGS=-std=c++17 -Wshadow -Wall -D_GLIBCXX_DEBUG

all: d

d: d.cpp
	g++-13 $(CPP_FLAGS) -g d.cpp -o d

brute: brute.cpp
	g++-13 $(CPP_FLAGS) -g brute.cpp -o brute
	
gen: gen.cpp
	g++-13 $(CPP_FLAGS) -g gen.cpp -o gen
